/**
 * Imports a Keystone run export and checks it lands on real spawns.
 *
 * The fixture is generated by Keystone from a synthetic combat log whose kills
 * were drawn from this very dungeon data, so a correct importer should place
 * essentially all of it.
 */
import { readFileSync, existsSync } from 'node:fs'
import { parseRun, runToRoute, compareToPlan, forcesCurve } from '../lib/run'
import { emptyRoute, forcesFor } from '../lib/route'
import type { Dungeon } from '../lib/types'

let failed = 0
const check = (n: string, c: boolean, d = '') => {
  console.log(`  ${c ? 'ok  ' : 'FAIL'} ${n}${c || !d ? '' : `\n         ${d}`}`)
  if (!c) failed++
}

const RUN_FILE = process.env.RUN_FILE ?? `${process.env.HOME}/Developer/keystone/build/runs/2026-09-07-1601-kr-15.json`
if (!existsSync(RUN_FILE)) {
  console.log(`  skip  no run export at ${RUN_FILE} (npm run export-run in keystone)`)
  process.exit(0)
}

const run = parseRun(readFileSync(RUN_FILE, 'utf8'))
check('parses a Keystone export', run.format === 'keystone.run')
check('carries the key level', run.run.level > 0, `level=${run.run.level}`)

const dungeon: Dungeon = JSON.parse(
  readFileSync(`${process.cwd()}/public/data/dungeons/kings-rest.json`, 'utf8')
)
check('run is for this dungeon', run.run.challengeModeId === dungeon.mapID)

const imported = runToRoute(run, dungeon)
check('every pull became a route pull', imported.route.pulls.length === run.pulls.length,
  `${imported.route.pulls.length} vs ${run.pulls.length}`)

const placed = imported.route.pulls.reduce(
  (n, p) => n + Object.values(p.enemies).reduce((m, c) => m + c.length, 0), 0)
const killed = run.pulls.reduce((n, p) => n + p.kills.length, 0)
check('nearly every kill found a spawn', placed >= killed * 0.95, `${placed} of ${killed} placed`)
check('unmatched kills are reported, not hidden', Array.isArray(imported.unmatched))

// No spawn may appear in two pulls: a mob dies once.
const seen = new Set<string>()
let duplicate = false
for (const pull of imported.route.pulls) {
  for (const [enemyIdx, clones] of Object.entries(pull.enemies)) {
    for (const cloneIdx of clones) {
      const key = `${enemyIdx}:${cloneIdx}`
      if (seen.has(key)) duplicate = true
      seen.add(key)
    }
  }
}
check('no spawn is claimed twice', !duplicate)

// The route's own forces maths should agree with what Keystone counted.
const rows = forcesFor(imported.route, dungeon)
const routeTotal = rows.length ? rows[rows.length - 1].cumulative : 0
const logTotal = run.pulls[run.pulls.length - 1].cumulative
check('forces agree with the log', Math.abs(routeTotal - logTotal) <= logTotal * 0.05,
  `route ${routeTotal} vs log ${logTotal}`)
check('the key was over 100%', routeTotal > (dungeon.totalCount ?? 0),
  `${routeTotal} of ${dungeon.totalCount}`)

const curve = forcesCurve(run)
check('the forces curve rises', curve.length > 1 && curve[curve.length - 1].percent > curve[0].percent)

// An empty plan should read as "everything you pulled was off-plan".
const comparison = compareToPlan(emptyRoute(dungeon.idx), imported)
check('an empty plan skips nothing', comparison.skipped.length === 0)
check('an empty plan makes every pack extra', comparison.extra.length === comparison.pulledPacks,
  `${comparison.extra.length} extra of ${comparison.pulledPacks} pulled`)

// A plan built from the run itself should match it exactly.
const selfPlan = { ...emptyRoute(dungeon.idx), pulls: imported.route.pulls }
const perfect = compareToPlan(selfPlan, imported)
check('a plan equal to the run has nothing skipped', perfect.skipped.length === 0)
check('a plan equal to the run has nothing extra', perfect.extra.length === 0,
  `${perfect.extra.length} extra`)

console.log(failed ? `\n${failed} check(s) failed` : '\nAll run-import checks passed.')
process.exit(failed ? 1 : 0)
